// Maps team name to emoji flag
export const teamFlags: Record<string, string> = {
  Spain: "🇪🇸",
  Ecuador: "🇪🇨",
  Belgium: "🇧🇪",
  Colombia: "🇨🇴",
  Australia: "🇦🇺",
  Algeria: "🇩🇿",
  Switzerland: "🇨🇭",
  Argentina: "🇦🇷",
  Croatia: "🇭🇷",
  France: "🇫🇷",
  "New Zealand": "🇳🇿",
  Germany: "🇩🇪",
  Austria: "🇦🇹",
  Netherlands: "🇳🇱",
  England: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
  "Bosnia & Herzegovina": "🇧🇦",
  Turkey: "🇹🇷",
  Czechia: "🇨🇿",
  Qatar: "🇶🇦",
  Mexico: "🇲🇽",
  Uruguay: "🇺🇾",
  Curacao: "🇨🇼",
  Jordan: "🇯🇴",
  "South Africa": "🇿🇦",
  Sweden: "🇸🇪",
  Portugal: "🇵🇹",
  "Saudi Arabia": "🇸🇦",
  "Cape Verde": "🇨🇻",
  Senegal: "🇸🇳",
  "Ivory Coast": "🇨🇮",
  DRC: "🇨🇩",
  Norway: "🇳🇴",
  Morocco: "🇲🇦",
  Brazil: "🇧🇷",
  Japan: "🇯🇵",
  Canada: "🇨🇦",
  Ghana: "🇬🇭",
  Iran: "🇮🇷",
  Scotland: "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
  "South Korea": "🇰🇷",
  Paraguay: "🇵🇾",
  Iraq: "🇮🇶",
  Panama: "🇵🇦",
  USA: "🇺🇸",
  Uzbekistan: "🇺🇿",
  Tunisia: "🇹🇳",
  Haiti: "🇭🇹",
  Egypt: "🇪🇬",
};

export function getFlag(teamName: string): string {
  return teamFlags[teamName] ?? "🏳️";
}
